/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orai0408;

import java.util.Random;

/**
 *
 * @author Win10
 */
public class Ablak extends javax.swing.JFrame {

    /**
     * Creates new form Ablak
     */
    public Ablak() {
        initComponents();
            setTitle("Alapműveletek");
        btOk.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbMuveletek = new javax.swing.JLabel();
        tfVartEredmeny = new javax.swing.JTextField();
        pnPanel = new javax.swing.JPanel();
        spScroll = new javax.swing.JScrollPane();
        taAlapmuvelet = new javax.swing.JTextArea();
        btOk = new javax.swing.JButton();
        btFeladat = new javax.swing.JButton();
        pnStat = new javax.swing.JPanel();
        lbKerdesCim = new javax.swing.JLabel();
        lbProbalkozasCim = new javax.swing.JLabel();
        lbSzazalekCim = new javax.swing.JLabel();
        lbVisszajelzesCim = new javax.swing.JLabel();
        szazalek = new javax.swing.JLabel();
        kerdes = new javax.swing.JLabel();
        visszajelzes = new javax.swing.JLabel();
        probalkozas = new javax.swing.JLabel();
        lbCim = new javax.swing.JLabel();
        lbOsztando = new javax.swing.JLabel();
        lbMuvelet = new javax.swing.JLabel();
        lbOszto = new javax.swing.JLabel();
        lbJel = new javax.swing.JLabel();
        mbMenuBar = new javax.swing.JMenuBar();
        mMenu = new javax.swing.JMenu();
        mSzorzas = new javax.swing.JMenu();
        mOsztas = new javax.swing.JMenu();
        mKivovas = new javax.swing.JMenu();
        mOsszeadas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfVartEredmeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVartEredmenyActionPerformed(evt);
            }
        });

        pnPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnPanel.setForeground(new java.awt.Color(255, 255, 255));

        taAlapmuvelet.setColumns(20);
        taAlapmuvelet.setRows(5);
        spScroll.setViewportView(taAlapmuvelet);

        javax.swing.GroupLayout pnPanelLayout = new javax.swing.GroupLayout(pnPanel);
        pnPanel.setLayout(pnPanelLayout);
        pnPanelLayout.setHorizontalGroup(
            pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spScroll)
        );
        pnPanelLayout.setVerticalGroup(
            pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btFeladat.setText("Új feladat");
        btFeladat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFeladatActionPerformed(evt);
            }
        });

        lbKerdesCim.setText("Kérdés:");

        lbProbalkozasCim.setText("Próbálkozások száma:");

        lbSzazalekCim.setText("Százalékos arány:");

        lbVisszajelzesCim.setText("Visszajelzés:");

        szazalek.setBackground(new java.awt.Color(255, 255, 255));
        szazalek.setForeground(new java.awt.Color(0, 0, 0));

        kerdes.setBackground(new java.awt.Color(255, 255, 255));
        kerdes.setForeground(new java.awt.Color(0, 0, 0));

        visszajelzes.setForeground(new java.awt.Color(0, 0, 0));

        probalkozas.setBackground(new java.awt.Color(255, 255, 255));
        probalkozas.setForeground(new java.awt.Color(0, 0, 0));

        lbCim.setText("Statisztika");

        javax.swing.GroupLayout pnStatLayout = new javax.swing.GroupLayout(pnStat);
        pnStat.setLayout(pnStatLayout);
        pnStatLayout.setHorizontalGroup(
            pnStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnStatLayout.createSequentialGroup()
                        .addComponent(lbSzazalekCim)
                        .addGap(18, 18, 18)
                        .addComponent(szazalek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnStatLayout.createSequentialGroup()
                        .addGroup(pnStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnStatLayout.createSequentialGroup()
                                .addComponent(lbVisszajelzesCim)
                                .addGap(18, 18, 18)
                                .addComponent(visszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnStatLayout.createSequentialGroup()
                                .addComponent(lbProbalkozasCim)
                                .addGap(18, 18, 18)
                                .addComponent(probalkozas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(pnStatLayout.createSequentialGroup()
                        .addComponent(lbKerdesCim)
                        .addGap(18, 18, 18)
                        .addGroup(pnStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnStatLayout.createSequentialGroup()
                                .addComponent(lbCim)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(kerdes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );
        pnStatLayout.setVerticalGroup(
            pnStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStatLayout.createSequentialGroup()
                .addComponent(lbCim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbKerdesCim)
                    .addComponent(kerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbProbalkozasCim)
                    .addComponent(probalkozas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSzazalekCim)
                    .addComponent(szazalek, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbVisszajelzesCim)
                    .addComponent(visszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        lbJel.setText("=");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbMuveletek, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addGap(94, 94, 94))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbOsztando)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMuvelet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbOszto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbJel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(tfVartEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btOk))
                    .addComponent(pnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btFeladat, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pnStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(pnStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMuveletek)
                            .addComponent(tfVartEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btOk)
                            .addComponent(lbOsztando)
                            .addComponent(lbMuvelet)
                            .addComponent(lbOszto)
                            .addComponent(lbJel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btFeladat, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        mMenu.setText("Menü");

        mSzorzas.setText("Szorzás");
        mMenu.add(mSzorzas);

        mOsztas.setText("Osztás");
        mOsztas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOsztasActionPerformed(evt);
            }
        });
        mMenu.add(mOsztas);

        mKivovas.setText("Kivonás");
        mMenu.add(mKivovas);

        mOsszeadas.setText("Összeadás");
        mMenu.add(mOsszeadas);

        mbMenuBar.add(mMenu);

        setJMenuBar(mbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfVartEredmenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVartEredmenyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVartEredmenyActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
//               String eredmeny = tfVartEredmeny.getText().trim();
//    String valasz = "2";
//        if (eredmeny.equals(valasz)) {
//           kerdes.setText("1");
//           probalkozas.setText("1");
//           szazalek.setText("100%");
//           visszajelzes.setText("Jó");
//        }
//        else {
//        kerdes.setText("1");
//           probalkozas.setText("1");
//           szazalek.setText("0%");
//           visszajelzes.setText("Rossz");
//        }


int oszto = Integer.parseInt(lbOszto.getText());
int osztando = Integer.parseInt(lbOsztando.getText());
int eredmeny = osztando / oszto;
int valasz = Integer.parseInt(tfVartEredmeny.getText());
int kerdesstat = 0;
int probalkozasstat = 0;
int szazalekstat = 0;


        System.out.println(oszto);
        System.out.println(osztando);
        System.out.println(eredmeny);
        System.out.println(valasz);
        
        if (eredmeny == valasz) {
             kerdesstat++;
            probalkozasstat++;
            szazalek.setText("100%");
            probalkozas.setText("1");
            kerdes.setText("1");
            visszajelzes.setText("Jó");
           
        }else{
              kerdesstat++;
            probalkozasstat++;
          szazalek.setText("0%");
            probalkozas.setText("1");
            kerdes.setText("1");
            visszajelzes.setText("Rossz");
        }

    }//GEN-LAST:event_btOkActionPerformed

    private void btFeladatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFeladatActionPerformed
//           lbMuveletek.setText("4/2=");
       btOk.setEnabled(true);
        osztas();
    }//GEN-LAST:event_btFeladatActionPerformed

    private void mOsztasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOsztasActionPerformed
       
    }//GEN-LAST:event_mOsztasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFeladat;
    private javax.swing.JButton btOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kerdes;
    private javax.swing.JLabel lbCim;
    private javax.swing.JLabel lbJel;
    private javax.swing.JLabel lbKerdesCim;
    private javax.swing.JLabel lbMuvelet;
    private javax.swing.JLabel lbMuveletek;
    private javax.swing.JLabel lbOsztando;
    private javax.swing.JLabel lbOszto;
    private javax.swing.JLabel lbProbalkozasCim;
    private javax.swing.JLabel lbSzazalekCim;
    private javax.swing.JLabel lbVisszajelzesCim;
    private javax.swing.JMenu mKivovas;
    private javax.swing.JMenu mMenu;
    private javax.swing.JMenu mOsszeadas;
    private javax.swing.JMenu mOsztas;
    private javax.swing.JMenu mSzorzas;
    private javax.swing.JMenuBar mbMenuBar;
    private javax.swing.JPanel pnPanel;
    private javax.swing.JPanel pnStat;
    private javax.swing.JLabel probalkozas;
    private javax.swing.JScrollPane spScroll;
    private javax.swing.JLabel szazalek;
    private javax.swing.JTextArea taAlapmuvelet;
    private javax.swing.JTextField tfVartEredmeny;
    private javax.swing.JLabel visszajelzes;
    // End of variables declaration//GEN-END:variables

    private void osztas() {
        boolean oszhato_e=false;
        Random rnd = new Random();
        int also=0;
        int felso=100;
         int osztando = rnd.nextInt(felso-also)+also;
        int oszto;
        do {            
            oszto= rnd.nextInt(felso-also)+also+1;
            if (osztando%oszto == 0) {
                oszhato_e=true;
            }
        } while (!oszhato_e);
        lbOszto.setText(oszto + "");
        lbOsztando.setText(osztando + "");
       lbMuvelet.setText("/");
       
    }
}
